import ListBoardComponentHeader from "@/components/ListBoardComponentHeader";
import "./globals.css";
import TodoCardComponent from "@/components/TodoCardComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        <ListBoardComponentHeader />
        <TodoCardComponent/>
        {children}
      </body>
    </html>
  );
}
